FROM bitnami/minideb:stretch as builder

RUN apt update
RUN apt install -y pkg-config libpcsclite-dev curl gcc
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y

RUN /root/.cargo/bin/rustup component add rustfmt
RUN mkdir /rustica
COPY proto /tmp/proto
COPY rustica /tmp/rustica
WORKDIR /tmp/rustica

RUN /root/.cargo/bin/cargo build --features="yubikey-support,webhook,amazon-kms,influx" --release


FROM bitnami/minideb:stretch
RUN apt update
RUN apt install -y libpcsclite-dev 

COPY --from=builder /tmp/rustica/target/release/rustica /rustica
USER 1000
ENTRYPOINT [ "/rustica" ]

